### PR TITLE
People list demo

### PR DESCRIPTION
**Pull request by jacob-jk**
I created a 'demo' version of what might be our Popular people page which later on we will connect to react router, once we create it. For now, I located it in App just to check, whether the layout is all right. Additionally, I created a folder in common dedicated to Pager.

### CODE REVIEW

**Review by anna-wojcik — CHANGES_REQUESTED** [review]
Add smaller gap between buttons in Pager when window is smaller and add media queries.
Gap between name of person should be less. Maybe use div instead of h2. Then use flex for div and align-items: flex-start to make the content to the top. 
When we have three person in the row, tiles are too big, maybe add new breakpoints or change the number of colums while you have too little space.

**Comment by jacob-jk** [comment]
thanks, those were good points. check whether there's something I forgot about, please

**Review by anna-wojcik — CHANGES_REQUESTED** [review]
- I would add padding to Section and change width of it otherwise 6 person will not fit in row.
src/common/Section/styled.js
export const Wrapper = styled.div`
  max-width: 1416px;
  margin: 56px auto;
  padding: 0 24px;

  @media (max-width: ${({ theme }) => theme.breakpoint.mobileMax}px) {
    margin: 24px 16px;
    padding: 0;
  }
`;

- change display to flex and add flex-direction (code below)
- delete margin in PeopleName 
- I realise that icons <, <<, >>, > should be in Pager.
- color font is hardly visible in Pager

**Comment by jacob-jk** [comment]
> * change display to flex and add flex-direction (code below)

what do you mean? which part of the code are you reffering to?

**Pull request merged**
